import { ThemeProvider } from "@/src/theme/ThemeProvider";
import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { clsx } from "clsx";
import { Header } from "@/src/feature/layout/Header";
import { Footer } from "@/src/feature/layout/Footer";
import Provider from "@/context/Provider"
import { getSession, useSession } from 'next-auth/react';


export async function getServerSideProps(context:any) {
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session
}: {
    children: React.ReactNode;
    session:any
  }) {

  return (
    <html lang="fr">
      <Provider  session={session}>
      <body className={clsx(inter.className, "bg-background")}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <div className="p-10">{children}</div>
          <Footer />
          </ThemeProvider>
        </body>
        </Provider>
      </html>
  );
}

